version: "3"

services:
  api:
    build: .
    container_name: fastapi-poker
    ports:
      - 8000:8000
    volumes:
      - .:/app

  redisdb:
    container_name: redisdb-poker
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
